print("    MENU     ")
print("1.soma")
print("2.subtração")
print("3.multiplicação")
print("4.divisão")
print("5.par ou ímpar")
print("6.fatorial")
print("7.primo")
print("0.sair")
opção=int(input("escolha uma opção do menu"))